### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [MG-RAST/DRISEE#8]
Hi I was trying to run DRISEE but ran into this error:

$ python DRISEE/drisee.py -g DRISEE/adapterDB.fna DRISEE/example_files/example_fasta results
Traceback (most recent call last):
  File "DRISEE/drisee.py", line 600, in <module>
    sys.exit(main(sys.argv))
  File "DRISEE/drisee.py", line 362, in main
    stats = seq_stats(in_seq, opts.seq_type, opts.verbose)
  File "DRISEE/drisee.py", line 111, in seq_stats
    fout, ferr = run_cmd(['seq_length_stats.py', '-f', '-i', in_file, '-t', fformat])
  File "DRISEE/drisee.py", line 86, in run_cmd
    proc = subprocess.Popen( cmd, stdout=output, stderr=subprocess.PIPE )
  File "//anaconda/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "//anaconda/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Any advice would be appreciated! Thank you.

**Comment by wltrimbl** [comment]
This error happens when some of DRISEE's scripts can't be found in the path while drisee.py is running.  Try amending the DRISEE directory to your path:

    export PATH=$PATH:/Users/CountvonCount/projects/DRISEE/

and try running again.

**Comment by brojpan** [comment]
Command:
`drisee.py --percent -n 3 -b 10000 -x 10000 -t fastq -s 149  ERR1457131.fastq error_rate_file`
Error:
```
Traceback (most recent call last):
  File "/home/borja/bin/DRISEE-1.2/drisee.py", line 585, in <module>
    sys.exit(main(sys.argv))
  File "/home/borja/bin/DRISEE-1.2/drisee.py", line 356, in main
    for seq_record in SeqIO.parse(DBFILE, "fasta"):
  File "/home/borja/.local/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 618, in parse
    with as_handle(handle, mode) as fp:
  File "/home/borja/bin/miniconda2/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/borja/.local/lib/python2.7/site-packages/Bio/File.py", line 101, in as_handle
    with open(handleish, mode, **kwargs) as fp:
IOError: [Errno 2] No such file or directory: 'adapterDB.fna'
```
I have the DRISEE directory in $PATH, bash can find the others scripts in the directory such as qiime-uclust or seq_lenght_stats.py.
